### ISSUE TITLE
Initialise library project for meta-diagram

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/PsyNeuLinkViewSource#24]
Added you as collaborator (admin in reality) to https://github.com/MetaCell/meta-diagram

- [x] initialise the yarn package
- [x] prepare library entry point
- [x] ensure this can be imported locally from another project as a depedency
- [x] prepare this for being published on npm
- [x] compile the README.

**Comment by afonsobspinto** [comment]
Done with https://github.com/MetaCell/meta-diagram/pull/4 cc @ddelpiano
